// Auth
export const AUTHENTICATED = 'AUTHENTICATED'

// User
export const INITIALIZE_USERS = 'INITIALIZE_USERS'
export const CREATE_USER = 'CREATE_USER'

//Classes
export const RECEIVE_CLASSES = 'RECEIVE_CLASSES'
export const RECEIVE_CLASS = 'RECEIVE_CURRENT_CLASS'

//Students
export const RECEIVE_STUDENT = 'RECEIVE_CURRENT_STUDENT'

//Notes
export const RECEIVE_NOTE = 'RECEIVE_CURRENT_NOTE'
